### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by ChipWolf** [authomatic/chromedriver_installer#4]
Isn't it possible to `pip install git+https://github.com/peterhudec/chromedriver_installer.git`?
If so, why are the extra steps for git clone etc. in the readme?

**Comment by alamsz** [comment]
@ChipWolf If I understand correctly your question, the steps for git clone if you want to use `python setup.py install` command, using this you could do some modification locally as necessary

if you want to use pip, just use `pip install chromedriver_installer`. 

FYI, if you use mac, chromedriver > 2.22 is using 64 bit architecture, while the code hardcoded 32 bit architecture for mac and it would not be possible using pip install directly for now, and need to use python setup.py install.
